config/routes.rb
Rails.application.routes.draw do
  root   'static_page#home'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, shallow: true do
    resources :lists
    resources :tasks do
      get :status_complite
      get :change_status
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :task, through: :relationships, dependent: :destroy

  default_scope -> { order(updated_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 16 }
  validates :description, presence: true, length: { minimum: 5, maximum: 100 }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @lists = current_user.lists
    @list = current_user.lists.find_by(id: params[:id])
    @list_tasks = @list.task.paginate(page: params[:page])
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.new(list_params)
    if @list.save
      flash[:success] = "List created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @list = current_user.lists.find_by(id: params[:id])
  end

  def update
    if @list.update_attributes(list_params)
      flash[:success] = "List updated"
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @list.destroy
    flash[:success] = "List deleted"
    redirect_to current_user
  end

private

  def list_params
    params.require(:list).permit(:title, :description, :user_id)
  end

  def correct_user
      @list = current_user.lists.find_by(id: params[:id])
      redirect_to root_url if @list.nil?
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, url: yield(:url) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/lists/edit.html.erb
<% provide(:title, 'Update list') %>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, list_path) %>
<h1>Update list</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/lists/new.html.erb
<% provide(:title, 'New list') %>
<% provide(:button_text, 'Create new list') %>
<% provide(:url, user_lists_path) %>
<h1>New list</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/lists/show.html.erb
<% provide(:title, current_user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= current_user.name %>
      </h1>
      <%= render 'shared/menu' %>
    </section>
  </aside>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-12 titlebox">
        <div class="col-md-10">
          <h3>
            <%= "#{@list.title}" %>
          </h3>
          <p>
            <%= "#{@list.description}" %>
          </p>
        </div>
      <div class="col-md-2">
        <%= link_to "Add new task", new_user_task_path(user_id: current_user.id), class: "btn btn-success new-task" %>
      </div>
    </div>
  </div>
  <% if @list_tasks.any? %>
    <ol class="tasks">
      <%= render @list_tasks %>
    </ol>
    <%= will_paginate @list_tasks %>
  <% end %>
  </div>
</div>