config/routes.rb
Rails.application.routes.draw do
  root   'static_page#home'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, shallow: true do
    resources :lists
    resources :tasks do
      get :status_complite
      get :change_status
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :list, through: :relationships, dependent: :destroy

  default_scope -> { order(updated_at: :desc) }
  validates :user_id, presence: true
  validates :title,   presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 250 }

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]
  include TasksHelper

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      @task_in_list = Relationship.new(list_params)
      @task_in_list.task_id = @task.id
      if @task_in_list.save
        flash[:success] = "Task created!"
        redirect_to current_user
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @task = current_user.tasks.find_by(id: params[:id])
  end

  def update
    if @task.update_attributes(task_params)
      @task_in_list = Relationship.find_by(task_id: params[:id])
      if @task_in_list.update_attributes(list_params)
        flash[:success] = "Task updated"
        redirect_to current_user
      else
        redirect_to current_user
      end
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task deleted"
    redirect_to request.referrer || current_user
  end

  def status_complite
    @task = current_user.tasks.find_by(id: params[:task_id])
    @task.update_attribute(:status, true)
    flash[:success] = "Status updated"
    redirect_to current_user
  end

  def change_status
    @task = current_user.tasks.find_by(id: params[:task_id])
    @task.update_attribute(:status, false)
    flash[:success] = "Status updated"
    redirect_to current_user
  end
private

  def task_params
    params.require(:task).permit(:title, :content, :user_id, :status)
  end

  def list_params
    params.require(:list).permit(:list_id, :task_id)
  end

    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to root_url if @task.nil?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def remember_status(task)
    task.remember_status
  end
end

app/views/tasks/_form.html.erb
<%= form_for @task, url: yield(:url) do |task| %>
  <%= render 'shared/error_messages', object: task.object %>

  <%= task.label :title %>
  <%= task.text_field :title, class: 'form-control' %>

  <%= task.label :content %>
  <%= task.text_field :content, class: 'form-control' %>

  <%= task.label :list_id %>
  <%= collection_select(:list, :list_id, current_user.lists, :id, :title) %>

  <%= task.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>", class="task-box" >
  <span class="title"><%= task.title %></span>
  <% if task.status == false %>
    <%= form_for task, url: task_status_complite_path(task_id: task.id), method: :get do |f| %>
      <%= f.submit 'Complite', class: "btn btn-success btn-xs btn-task-status", style: "float: right" %>
    <% end %>
  <% elsif task.status == true %>
    <%= form_for task, url: task_change_status_path(task_id: task.id), method: :get do |f| %>
      <%= f.submit 'Change status', class: "btn btn-primary btn-xs btn-task-status", style: "float: right" %>
    <% end %>
  <% end %>
  <span class="content"><%= task.content %></span><br>
  <span class="user">by <%= link_to task.user.name, task.user %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(task.updated_at) %> ago.
  </span>
  <% if current_user?(task.user) %>
  <span style="float: right">
    <%= link_to "Edit", edit_task_path(id: task.id), class: "btn btn-warning btn-xs btn-task" %>
    <%= link_to "Delete", task, method: :delete,
                                data: { confirm: "You sure?" },
                                class: "btn btn-danger btn-xs btn-task" %>
  </span>
  <% end %>
</li>

app/views/tasks/edit.html.erb
<% provide(:title, "Update task") %>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, task_path) %>
<h1>Update task</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/tasks/new.html.erb
<% provide(:title, 'New task') %>
<% provide(:button_text, 'Create new task') %>
<% provide(:url, user_tasks_path) %>
<h1>New task</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>