config/routes.rb
Rails.application.routes.draw do
  root   'static_page#home'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, shallow: true do
    resources :lists
    resources :tasks do
      get :status_complite
      get :change_status
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
  <ul class="side-menu">
    <li>
      <span class="glyphicon glyphicon-certificate" aria-hidden="true"></span>
      <%= link_to "My Day", '#' %>
    </li>
    <li>
      <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
      <%= link_to "Important", '#' %>
    </li>
    <li>
      <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
      <%= link_to "Planned", '#' %>
    </li>
    <li>
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
      <%= link_to "Assigned to you", '#' %>
    </li>
    <li>
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      <%= link_to "Tasks", '#' %>
    </li>
  </ul>

  <ul class="side-menu new">
    <li>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      <%= link_to "New list", new_user_list_path(user_id: current_user.id) %>
    </li>
  </ul>
  <% if current_user.lists.any? %>
  <ul class="side-menu">
    <% @lists.each do |list| %>
    <li id="list-<%= list.id %>">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      <%= link_to list.title, list_path(id: list.id) %>
      <%= link_to list, method: :delete,
                        data: { confirm: "You sure?" } do %>
        <span class="glyphicon glyphicon-trash glyphicon-option" style="float: right" aria-hidden="true"></span>
      <% end %>
      <%= link_to edit_list_path(id: list.id) do %>
        <span class="glyphicon glyphicon-pencil glyphicon-option" style="float: right" aria-hidden="true"></span>
      <% end %>
    </li>
    <% end %>
  </ul>
  <% end %>